// ignore_for_file: unnecessary_this, unused_import

import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:io';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class DoctorQualificationDetails with ChangeNotifier {
  List<String> AyurvedicList = [
    'Select the Department',
    'B.A.M.S (Bachelor of Ayurvedic Medicine and Surgery)',
    'Doctor of Medicine(Rachna Sharir)',
    'Doctor of Medicine(Dravya Guna)',
    'Doctor of Medicine(Ayurved Siddant& Darshan)',
    'Doctor of Medicine(Kayachikitsa)',
    'Doctor of Medicine(Vikruti Vidnyan and Rog Nidan)',
    'Doctor of Medicine(Panchakarma)',
    'Doctor of Medicine(Swastha Vritta)',
    'Doctor of Medicine(Bhaishajya Kalpana)',
    'Doctor of Medicine(Kriya Sharir)',
    'Doctor of Medicine(Kaumarya Bhritya Tantra)',
    'Doctor of Medicine(Agad Tantra)',
    'Master of Surgery(Shalakya Tantra)',
    'Master of Surgery(Prasuti Tantra and Stree Rog)',
    'Master of Surgery(Shalya Tantra)',
    'M.D. (Ayurved)',
  ];

  List<String> HomoeopathyList = [
    'Select the Department',
    'B.H.M.S ( Bachelor of Homeopathic Medicine and Surgery)',
    'Master of Dental Surgery in Prosthodontics & Crown & Bridge',
    'Master of Dental Surgery in Periodontology',
    'Master of Dental Surgery in Oral & Maxillofacial Surgery',
    'Master of Dental Surgery in Orthodontics & Dentofacial Orthopedics',
    'Master of Dental Surgery in Conservative Dentistry & Endodontics',
    'Master of Dental Surgery in Oral Pathology & Microbiology',
    'Master of Dental Surgery in Oral Medicine & Radiology',
    'Master of Dental Surgery in Paedodontics and Preventive Dentistry',
  ];

  List<String> YogicList = [
    'Select the Department',
    'B.N.Y.S (Bachelor of Naturopathy and Yogic Sciences)'
  ];

  List<String> SiddhaList = [
    'Select the Department',
    'B.S.M.S (Bachelor of Siddha Medicine and Surgery)',
    'M.D. (Siddha)',
    'B.T.M.S (Bachelor in Tibetan Medical System or Amchi Chikitsa Acharya)',
  ];

  List<String> UnnaiList = [
    'Select the Department',
    'B.U.M.S (Bachelor in Unani Medicine and Surgery)',
    'M.D. (Unani Medicine)'
  ];

  List<String> AllopathyListWith_MBBS_Degree_List = [
    'Select the Department',
    'M.B.B.S',
    'Diploma in Oto-Rhino-Laryngology',
    'Diploma in Radio-Diagnosis',
    'Diploma in Radio Therapy',
    'Diploma in Medical Virology',
    'Diploma in Occupational Health',
    'Diploma in Ophthalmology',
    'Diploma in Orthopaedics',
    'Diploma in Public Health',
    'Diploma in Physical Medicine and Rehabilitation',
    'Diploma in Psychological Medicine',
    'Diploma in Radiation Medicine',
    'Diploma in Sports Medicine',
    'Diploma in Tuberculosis and Chest Diseases',
    'Diploma in Tropical Medicine Health',
    'Diploma in Dermatology, Venereology and Leprosy',
    'Diploma in Venereology',
    'Diploma in Paediatrics',
    'Diploma - Aviation Medicine',
    'Diploma in Cardiology',
    'Diploma in Basic Medical Sciences (Anatomy)',
    'Diploma in Basic Medical Sciences (Physiology)',
    'Diploma in Basic Medical Sciences (Pharmacology)',
    'Diploma in Maternity and Child Welfare',
    'Diploma -Diploma V and D',
    'Diploma in Medical Radioligy and Electrology',
    'Diploma - Diploma in Pathology and Bacteriology',
    'Diploma in Microbiology',
    'Diploma in Path. and Bact',
    'Diploma in Industrial Health',
    'Diploma in Allergy and Clinical Immunology',
    'Diploma in Anesthesia',
    'Diploma in Child Health',
    'Diploma in Community Medicine',
    'Diploma in Clinical Pathology',
    'Diploma in Dermatology',
    'Diploma in Diabetology',
    'Diploma in Forensic Medicine',
    'Diploma in Health Administration',
    'Diploma in Hospital Administration',
    'Diploma in Health Education',
    'Diploma in Immuno-Haematology and Blood Transfusion',
    'Diploma in Leprosy',
    'Diploma (Marine Medicine)',
  ];

  List<String> AllopathyListWith_MBBS_POST_GRADUATE_Degree_List = [
    'Select the Department',
    'MD - Tropical Medicine',
    'MD - Maternity and Child Health',
    'MD - CCM (CERTIFICATE COURSE MACHINING )',
    'MD - Sports Medicine',
    'MD-Transfusion Medicine',
    'MD - Immuno Haematology and Blood Transfusion',
    'Master of Public Health (Epidemiology) With basic degree as MBBS',
    'MD - Anaesthesiology',
    'MD - Aviation Medicine',
    'MD - Bio-Chemistry',
    'MD - Bio-Physics',
    'MD - Forensic Medicine/Forensic Medicine and Toxicology',
    'MD - General Medicine',
    'MD - Community Health Administration',
    'MD - Geriatrics',
    'MD - Hospital Administration',
    'MD - Lab Medicine',
    'MD - Microbiology',
    'MD - Nuclear Medicine',
    'MD - Obstetrtics and Gynaecology',
    'MD - Paediatrics',
    'MD - Dermatology , Venereology and Leprosy',
    'MD - Pharmacology',
    'MD - Physiology',
    'MD - Physical Medicine and Rehabilitation',
    'MD - Psychiatry',
    'MD - Radiotherapy',
    'MD - Social and Preventive Medicine / Community Medicine',
    'MD - Venereology',
    'MD - Pathology and Microbiology',
    'MD - Emergency Medicine',
    'MD - Family Medicine',
    'MD - Radio Diagnosis/Radiology',
    'MD - Aviation Medicine/Aerospace Medicine',
    'MD - Rheumatology',
    'MD - Palliative Medicine',
    'MD/MS - Obstetrtics and Gynaecology',
    'MS - Orthopaedics',
    'MS - ENT',
    'MS - General Surgery',
    'MD/MS - Anatomy',
    'MD/MS - Ophthalmology',
    'Master of Hospital Administration (with basic degree as MBBS)',
    'Master Degree in Applied Epidemiology (with basic degree as MBBS)',
    'Master of Public Health (with basic degree as MBBS)',
  ];

  List<String> AllopathyListWith_MBBS_SUPER_SPECIALTY_in_DM_MCH_Degree_List = [
    'Select the Department',
    'DM - Neurology',
    'DM - Rheumatology',
    'DM - Endocrinology',
    'DM - Clinical Immunology',
    'DM - Pul. Med. and Critical Care Med',
    'DM - Cardiac-Anaes.',
    'DM - Haematology Pathology/Hematopthology',
    'DM - Medical Genetics',
    'DM - Organ Transplant Anaesthesia and Critical Care',
    'DM - Critical Care Medicine',
    'DM - Paediatric Hepatology',
    'DM - Paediatric Neurology',
    'DM - Neuro Anaesthesia',
    'DM - Paediatric Nephrology',
    'DM - Reproductive Medicine',
    'DM - Infectious Disease',
    'DM - Paediatric Oncology',
    'DM - Geriatric Mental Health',
    'DM - Paediatric Critical Care',
    'DM - Paediatric Haematology Oncology',
    'DM - Paediatric and Neonatal Anaesthesia',
    'DM - Clinical Pharmacology',
    'DM - Clinical Haematology',
    'DM - Pulmonary Medicine',
    'DM - Neuro Radiology',
    'DM - Nephrology',
    'DM - Neonatology',
    'DM - Oncology',
    'DM - Gastroenterology',
    'DM - Cardiology',
    'DM - Infectious Diseases',
    'DM - Hepatology',
    'DM - Immunology',
    'DM - Pediatrics Gastroenterology',
    'DM - Pediatrics Cardiology',
    'M.Ch - Endocrine Surgery',
    'M.Ch. - Hand and Micro Surgery',
    'M.Ch. - Hand Surgery',
    'M.Ch. - Head and Neck Surgery',
    'M.Ch - Vascular Surgery',
    'M.Ch - Cardio Thoracic Surgery',
    'M.Ch - Cardio Thoracic and Vascular Surgery',
    'M.Ch - Neuro Surgery',
    'M.Ch - Paediatric Surgery',
    'M.Ch - Plastic Surgery',
    'M.Ch - Surgical Gastroenterology/G.I. Surgery',
    'M.Ch - Surgical Oncology',
    'M.Ch - Thoracic Surgery',
    'M.Ch - Hepato Pancreato Biliary Surgery',
    'M.Ch - Urology/Genito-Urinary Surgery',
    'M.Ch - Gynaecological Oncology',
    'M.Ch - Pediatric Cardio-Thoracic Vascular Surgery',
  ];

  List<String> AllopathyList = [
    'Select the Department',
    'M.B.B.S',
    'Diploma in Oto-Rhino-Laryngology',
    'Diploma in Radio-Diagnosis',
    'Diploma in Radio Therapy',
    'Diploma in Medical Virology',
    'Diploma in Occupational Health',
    'Diploma in Ophthalmology',
    'Diploma in Orthopaedics',
    'Diploma in Public Health',
    'Diploma in Physical Medicine and Rehabilitation',
    'Diploma in Psychological Medicine',
    'Diploma in Radiation Medicine',
    'Diploma in Sports Medicine',
    'Diploma in Tuberculosis and Chest Diseases',
    'Diploma in Tropical Medicine Health',
    'Diploma in Dermatology, Venereology and Leprosy',
    'Diploma in Venereology',
    'Diploma in Paediatrics',
    'Diploma - Aviation Medicine',
    'Diploma in Cardiology',
    'Diploma in Basic Medical Sciences (Anatomy)',
    'Diploma in Basic Medical Sciences (Physiology)',
    'Diploma in Basic Medical Sciences (Pharmacology)',
    'Diploma in Maternity and Child Welfare',
    'Diploma -Diploma V and D',
    'Diploma in Medical Radioligy and Electrology',
    'Diploma - Diploma in Pathology and Bacteriology',
    'Diploma in Microbiology',
    'Diploma in Path. and Bact',
    'Diploma in Industrial Health',
    'Diploma in Allergy and Clinical Immunology',
    'Diploma in Anesthesia',
    'Diploma in Child Health',
    'Diploma in Community Medicine',
    'Diploma in Clinical Pathology',
    'Diploma in Dermatology',
    'Diploma in Diabetology',
    'Diploma in Forensic Medicine',
    'Diploma in Health Administration',
    'Diploma in Hospital Administration',
    'Diploma in Health Education',
    'Diploma in Immuno-Haematology and Blood Transfusion',
    'Diploma in Leprosy',
    'Diploma (Marine Medicine)',
    'MD - Tropical Medicine',
    'MD - Maternity and Child Health',
    'MD - CCM (CERTIFICATE COURSE MACHINING )',
    'MD - Sports Medicine',
    'MD-Transfusion Medicine',
    'MD - Immuno Haematology and Blood Transfusion',
    'Master of Public Health (Epidemiology) With basic degree as MBBS',
    'MD - Anaesthesiology',
    'MD - Aviation Medicine',
    'MD - Bio-Chemistry',
    'MD - Bio-Physics',
    'MD - Forensic Medicine/Forensic Medicine and Toxicology',
    'MD - General Medicine',
    'MD - Community Health Administration',
    'MD - Geriatrics',
    'MD - Hospital Administration',
    'MD - Lab Medicine',
    'MD - Microbiology',
    'MD - Nuclear Medicine',
    'MD - Obstetrtics and Gynaecology',
    'MD - Paediatrics',
    'MD - Dermatology , Venereology and Leprosy',
    'MD - Pharmacology',
    'MD - Physiology',
    'MD - Physical Medicine and Rehabilitation',
    'MD - Psychiatry',
    'MD - Radiotherapy',
    'MD - Social and Preventive Medicine / Community Medicine',
    'MD - Venereology',
    'MD - Pathology and Microbiology',
    'MD - Emergency Medicine',
    'MD - Family Medicine',
    'MD - Radio Diagnosis/Radiology',
    'MD - Aviation Medicine/Aerospace Medicine',
    'MD - Rheumatology',
    'MD - Palliative Medicine',
    'MD/MS - Obstetrtics and Gynaecology',
    'MS - Orthopaedics',
    'MS - ENT',
    'MS - General Surgery',
    'MD/MS - Anatomy',
    'MD/MS - Ophthalmology',
    'Master of Hospital Administration (with basic degree as M.B.B.S)',
    'Master Degree in Applied Epidemiology (with basic degree as M.B.B.S)',
    'Master of Public Health (with basic degree as MBBS)',
    'DM - Neurology',
    'DM - Rheumatology',
    'DM - Endocrinology',
    'DM - Clinical Immunology',
    'DM - Pul. Med. and Critical Care Med',
    'DM - Cardiac-Anaes.',
    'DM - Haematology Pathology/Hematopthology',
    'DM - Medical Genetics',
    'DM - Organ Transplant Anaesthesia and Critical Care',
    'DM - Critical Care Medicine',
    'DM - Paediatric Hepatology',
    'DM - Paediatric Neurology',
    'DM - Neuro Anaesthesia',
    'DM - Paediatric Nephrology',
    'DM - Reproductive Medicine',
    'DM - Infectious Disease',
    'DM - Paediatric Oncology',
    'DM - Geriatric Mental Health',
    'DM - Paediatric Critical Care',
    'DM - Paediatric Haematology Oncology',
    'DM - Paediatric and Neonatal Anaesthesia',
    'DM - Clinical Pharmacology',
    'DM - Clinical Haematology',
    'DM - Pulmonary Medicine',
    'DM - Neuro Radiology',
    'DM - Nephrology',
    'DM - Neonatology',
    'DM - Oncology',
    'DM - Gastroenterology',
    'DM - Cardiology',
    'DM - Infectious Diseases',
    'DM - Hepatology',
    'DM - Immunology',
    'DM - Pediatrics Gastroenterology',
    'DM - Pediatrics Cardiology',
    'M.Ch - Endocrine Surgery',
    'M.Ch. - Hand and Micro Surgery',
    'M.Ch. - Hand Surgery',
    'M.Ch. - Head and Neck Surgery',
    'M.Ch - Vascular Surgery',
    'M.Ch - Cardio Thoracic Surgery',
    'M.Ch - Cardio Thoracic and Vascular Surgery',
    'M.Ch - Neuro Surgery',
    'M.Ch - Paediatric Surgery',
    'M.Ch - Plastic Surgery',
    'M.Ch - Surgical Gastroenterology/G.I. Surgery',
    'M.Ch - Surgical Oncology',
    'M.Ch - Thoracic Surgery',
    'M.Ch - Hepato Pancreato Biliary Surgery',
    'M.Ch - Urology/Genito-Urinary Surgery',
    'M.Ch - Gynaecological Oncology',
    'M.Ch - Pediatric Cardio-Thoracic Vascular Surgery',

  ];

  List<String> getDepartmentList(String docDepartment) {
    if (docDepartment.toLowerCase() == "Ayurvedic".toLowerCase()) {
      return AyurvedicList;
    } else if (docDepartment.toLowerCase() == "Homeopathy".toLowerCase()) {
      return HomoeopathyList;
    } else if (docDepartment.toLowerCase() == "Yogic".toLowerCase()) {
      return YogicList;
    } else if (docDepartment.toLowerCase() == "Siddha".toLowerCase()) {
      return SiddhaList;
    } else if (docDepartment.toLowerCase() == "Unani".toLowerCase()) {
      return UnnaiList;
    } else {
      return AllopathyList;
    }
  }
}
